<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="true" CodeBehind="ManageCoupons.aspx.cs" Inherits="Respace.Admin.ManageCoupons" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div style="padding: 24px;">
        <h2 class="h2">Issued Coupons Log</h2>
        <p class="muted">Viewing all unique voucher codes generated by guests.</p>

        <div class="card">
            <asp:GridView ID="gvUserCoupons" runat="server" AutoGenerateColumns="False" CssClass="table" GridLines="None">
                <Columns>
                    <asp:BoundField DataField="UserCouponId" HeaderText="ID" />
                    <asp:BoundField DataField="UserId" HeaderText="User ID" />
                    <asp:BoundField DataField="CouponCode" HeaderText="Voucher Code" />
                    <asp:BoundField DataField="DiscountAmount" HeaderText="Value" DataFormatString="${0}" />
                    <asp:TemplateField HeaderText="Status">
                        <ItemTemplate>
                            <span class='<%# Convert.ToBoolean(Eval("IsUsed")) ? "badge-used" : "badge-active" %>'>
                                <%# Convert.ToBoolean(Eval("IsUsed")) ? "Used" : "Active" %>
                            </span>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:BoundField DataField="RedeemedAt" HeaderText="Generated On" DataFormatString="{0:dd MMM yyyy}" />
                </Columns>
            </asp:GridView>
        </div>
    </div>

    <style>
        .badge-active { color: #28a745; font-weight: bold; }
        .badge-used { color: #666; font-style: italic; }
    </style>
</asp:Content>